name: Developer_Pull_Request_CI
on:
  pull_request:
    branches:
      - 'main'

jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: ls
      - run: tail index.js