name: Developer_Branch_CI
on:
  push:
    branches:
      - 'XPNS-*'

jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: ls
      - run: tail index.js